In [ ]:
import numpy as np
Sales=np.array([22,44,56,78,90])
print(Sales)

[22 44 56 78 90]


In [ ]:
import numpy as np
Marks=np.array([70,85,85,91,98])
print(Marks)

[70 85 85 91 98]


In [ ]:
marks=np.array([[70,85,85,98],[88,99,99,99],[67,89,76,90]])
print(marks)

print(marks.ndim)

print(marks.shape)

print(marks.size)

print(marks.dtype)

[[70 85 85 98]
 [88 99 99 99]
 [67 89 76 90]]
2
(3, 4)
12
int64


In [ ]:
print(marks>40)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
print(marks[marks>40])

[70 85 85 98 88 99 99 99 67 89 76 90]


In [ ]:
import pandas as pd

s1=pd.Series([23,56,78,94,34])

print(s1)

0    23
1    56
2    78
3    94
4    34
dtype: int64


In [ ]:
import pandas as pd
Student_Name=pd.Series(["Ram","Shyam","Shita","Geeta"])
print(Student_Name)

0      Ram
1    Shyam
2    Shita
3    Geeta
dtype: object


In [ ]:
import pandas as pd
Student_Name=pd.Series([23,56,78,94],index=["Ram","Shyam","Shita","Geeta"])
print(Student_Name)

Ram      23
Shyam    56
Shita    78
Geeta    94
dtype: int64


s=[100,200,300,400,500,600,700]

day=["Mon","Tues","Wed","Thur","Fri","Sat","Sun"]

Sales=pd.Series(s,index=day)

print(Sales["Tues"])

# take  day name from the user then check  it is in day list or not if is in day list then show

# sales otherwise print invalid day (In )

In [ ]:
sales=[100,200,300,400,500,600,700]
Days=["Mon","Tues","Wed","Thur","Fri","Sat","Sun"]
Sales=pd.Series(sales,index=Days)
print(Sales)

Mon     100
Tues    200
Wed     300
Thur    400
Fri     500
Sat     600
Sun     700
dtype: int64


In [ ]:
sales=[100,200,300,400,500,600,700]
Days=["Mon","Tues","Wed","Thur","Fri","Sat","Sun"]
Sales=pd.Series(sales,index=Days)
print(Sales)
User=input("Enter the Day:")
if (User in Days):
    print(Sales[User])
else:
    print("Invalid Day")

Mon     100
Tues    200
Wed     300
Thur    400
Fri     500
Sat     600
Sun     700
dtype: int64
Enter the Day:sat
Invalid Day


In [ ]:
print(Sales[Sales>400])


Fri    500
Sat    600
Sun    700
dtype: int64


In [ ]:
print(Sales.sum())
print(Sales.mean())
print(Sales.max())
print(Sales.min())

2800
400.0
700
100


In [ ]:
print(Sales.head(2))

Mon     100
Tues    200
dtype: int64


In [ ]:
print(Sales.tail(2))

Sat    600
Sun    700
dtype: int64


In [ ]:
import numpy as np

s=[100,np.nan,300,400,500,np.nan,700]

day=["Mon","Tues","Wed","Thur","Fri","Sat","Sun"]

Sales=pd.Series(s,index=day)

print(Sales["Tues"])

nan


In [ ]:
import numpy as np

s=[100,np.nan,300,400,500,np.nan,700]

day=["Mon","Tues","Wed","Thur","Fri","Sat","Sun"]

Sales=pd.Series(s,index=day)

print(Sales)


Mon     100.0
Tues      NaN
Wed     300.0
Thur    400.0
Fri     500.0
Sat       NaN
Sun     700.0
dtype: float64


In [ ]:
print(Sales.isnull())

Mon     False
Tues     True
Wed     False
Thur    False
Fri     False
Sat      True
Sun     False
dtype: bool


In [ ]:
print(Sales.isnull().sum())

2


In [ ]:
import numpy as np

s=[100,np.nan,300,400,500,np.nan,700]

day=["Mon","Tues","Wed","Thur","Fri","Sat","Sun"]

Sales=pd.Series(s,index=day)

#print(Sales)

#print(Sales.isnull())



print(Sales.isnull().sum())    #   2





#Sales=Sales.dropna()

#Sales=Sales.fillna(0)

Sales=Sales.fillna(Sales.max())



print(Sales.isnull().sum())

print(Sales)

2
0
Mon     100.0
Tues    700.0
Wed     300.0
Thur    400.0
Fri     500.0
Sat     700.0
Sun     700.0
dtype: float64


In [ ]:
Sales=Sales.fillna(Sales.max())
print(Sales)

Mon     100.0
Tues      0.0
Wed     300.0
Thur    400.0
Fri     500.0
Sat       0.0
Sun     700.0
dtype: float64


In [ ]:
import pandas as pd
users={"Name":["Ajay","Ram","Sita","Geeta","Radha"],

       "Email":["ajay@gmai.com","ram@gmai.com","sita@gmai.com","geeta@gmai.com","radha@gmai.com",],

       "Department":["IT","Sales","Administrator","DWS","Cloud"],

       "Salary":[28000,20000,35000,32000,50000]}

df=pd.DataFrame(users)

print(df)

    Name           Email     Department  Salary
0   Ajay   ajay@gmai.com             IT   28000
1    Ram    ram@gmai.com          Sales   20000
2   Sita   sita@gmai.com  Administrator   35000
3  Geeta  geeta@gmai.com            DWS   32000
4  Radha  radha@gmai.com          Cloud   50000


In [ ]:
print(df['Name'])

0     Ajay
1      Ram
2     Sita
3    Geeta
4    Radha
Name: Name, dtype: object


In [ ]:
print(df[['Name','Email']])

    Name           Email
0   Ajay   ajay@gmai.com
1    Ram    ram@gmai.com
2   Sita   sita@gmai.com
3  Geeta  geeta@gmai.com
4  Radha  radha@gmai.com


In [ ]:
print(df[['Name','Salary','Department']])

    Name  Salary     Department
0   Ajay   28000             IT
1    Ram   20000          Sales
2   Sita   35000  Administrator
3  Geeta   32000            DWS
4  Radha   50000          Cloud


In [ ]:
city=["Delhi","Bangalore","Pune","Mumbai","Noida"]
df=pd.DataFrame(users)
df['City']=city
print(df)

      Name              Email    Password Department  Salary       City
0  Sharath  Sharath@gmail.com  Sharath123      sales   40000      Delhi
1    Rohit    Rohit@gmail.com    Rohit123      Admin   50000  Bangalore
2    sudha    sudha@gmail.com    sudha123         HR   60000       Pune
3    vijay    vijay@gmail.com    vijay123    Finance   70000     Mumbai
4   sanjay   sanjay@gmail.com   sanjay123   purchase   80000      Noida


In [ ]:
df['Bonuse']=df['Salary']*10/100
print(df)

      Name              Email    Password Department  Salary       City  \
0  Sharath  Sharath@gmail.com  Sharath123      sales   40000      Delhi   
1    Rohit    Rohit@gmail.com    Rohit123      Admin   50000  Bangalore   
2    sudha    sudha@gmail.com    sudha123         HR   60000       Pune   
3    vijay    vijay@gmail.com    vijay123    Finance   70000     Mumbai   
4   sanjay   sanjay@gmail.com   sanjay123   purchase   80000      Noida   

   Bonuse  
0  4000.0  
1  5000.0  
2  6000.0  
3  7000.0  
4  8000.0  


In [ ]:
df['Tot_Sal']=df['Salary']+df['Bonuse']
print(df)

      Name              Email    Password Department  Salary       City  \
0  Sharath  Sharath@gmail.com  Sharath123      sales   40000      Delhi   
1    Rohit    Rohit@gmail.com    Rohit123      Admin   50000  Bangalore   
2    sudha    sudha@gmail.com    sudha123         HR   60000       Pune   
3    vijay    vijay@gmail.com    vijay123    Finance   70000     Mumbai   
4   sanjay   sanjay@gmail.com   sanjay123   purchase   80000      Noida   

   Bonuse  Tot_Sal  
0  4000.0  44000.0  
1  5000.0  55000.0  
2  6000.0  66000.0  
3  7000.0  77000.0  
4  8000.0  88000.0  


In [ ]:
print(df[df['Salary']>20000])

      Name              Email    Password Department  Salary       City  \
0  Sharath  Sharath@gmail.com  Sharath123      sales   40000      Delhi   
1    Rohit    Rohit@gmail.com    Rohit123      Admin   50000  Bangalore   
2    sudha    sudha@gmail.com    sudha123         HR   60000       Pune   
3    vijay    vijay@gmail.com    vijay123    Finance   70000     Mumbai   
4   sanjay   sanjay@gmail.com   sanjay123   purchase   80000      Noida   

   Bonuse  Tot_Sal  
0  4000.0  44000.0  
1  5000.0  55000.0  
2  6000.0  66000.0  
3  7000.0  77000.0  
4  8000.0  88000.0  


In [ ]:
print(df[df['City']=="Pune"])

    Name            Email  Password Department  Salary  City  Bonuse  Tot_Sal
2  sudha  sudha@gmail.com  sudha123         HR   60000  Pune  6000.0  66000.0


In [ ]:
print(df[df['Department']=="HR"])

    Name            Email  Password Department  Salary  City  Bonuse  Tot_Sal
2  sudha  sudha@gmail.com  sudha123         HR   60000  Pune  6000.0  66000.0


In [ ]:
# show email of user those working in HR dept
print(df[df['Department']=="HR"]['Email'])

2    sudha@gmail.com
Name: Email, dtype: object


In [ ]:
print(df[df['Department']=="Admin"][['Email','Password']])

             Email  Password
1  Rohit@gmail.com  Rohit123


In [ ]:
#show email id and password those those users who are woring in admin dept
print(df[(df['Department']=="Admin") & (df['Salary']>20000)])

    Name            Email  Password Department  Salary       City  Bonuse  \
1  Rohit  Rohit@gmail.com  Rohit123      Admin   50000  Bangalore  5000.0   

   Tot_Sal  
1  55000.0  


In [ ]:
# multiple condition
print(df[(df['Department']=="Admin") | (df['Salary']>20000)])

      Name              Email    Password Department  Salary       City  \
0  Sharath  Sharath@gmail.com  Sharath123      sales   40000      Delhi   
1    Rohit    Rohit@gmail.com    Rohit123      Admin   50000  Bangalore   
2    sudha    sudha@gmail.com    sudha123         HR   60000       Pune   
3    vijay    vijay@gmail.com    vijay123    Finance   70000     Mumbai   
4   sanjay   sanjay@gmail.com   sanjay123   purchase   80000      Noida   

   Bonuse  Tot_Sal  
0  4000.0  44000.0  
1  5000.0  55000.0  
2  6000.0  66000.0  
3  7000.0  77000.0  
4  8000.0  88000.0  


In [ ]:
import pandas as pd
data = {

    "Loan_ID": [

        1001, 1002, 1003, 1004, 1005,

        1006, 1007, 1008, 1009, 1010,

        1011, 1012, 1013, 1014, 1015,

        1016, 1017, 1018, 1019, 1020

    ],
    "Applicant_Name": [

        "Rahul Sharma", "Priya Verma", "Amit Kumar", "Neha Singh", "Rohan Mehta",

        "Anjali Gupta", "Vikas Yadav", "Sneha Kapoor", "Arjun Malhotra", "Pooja Jain",

        "Karan Patel", "Simran Kaur", "Manish Sharma", "Ritika Joshi", "Aditya Rao",

        "Nisha Agarwal", "Suresh Kumar", "Meena Rani", "Varun Gupta", "Kavita Singh"

    ],
    "Age": [

        28, 35, 42, 31, 29,

        45, 38, 27, 33, 40,

        36, 30, 48, 26, 34,

        39, 44, 32, 37, 41

    ],
    "Gender": [

        "Male", "Female", "Male", "Female", "Male",

        "Female", "Male", "Female", "Male", "Female",

        "Male", "Female", "Male", "Female", "Male",

        "Female", "Male", "Female", "Male", "Female"

    ],
    "Income": [

        45000, 60000, 75000, 52000, 48000,

        90000, 68000, 42000, 80000, 55000,

        72000, 65000, 95000, 40000, 70000,

        58000, 85000, 50000, 78000, 62000

    ],
    "Loan_Amount": [

        250000, 400000, 600000, 300000, 275000,

        800000, 500000, 200000, 650000, 350000,

        550000, 450000, 900000, 180000, 500000,

        375000, 700000, 280000, 620000, 420000

    ],
    "Loan_Term": [

        5, 10, 15, 7, 5,

        20, 15, 5, 20, 10,

        15, 10, 20, 5, 15,

        10, 20, 7, 15, 10

    ],
    "Credit_Score": [

        720, 680, 750, 690, 710,

        800, 740, 650, 780, 700,

        730, 690, 810, 640, 760,

        710, 790, 675, 745, 700

    ],

    "Employment_Type": [

        "Salaried", "Self-Employed", "Salaried", "Salaried", "Business",

        "Salaried", "Business", "Salaried", "Salaried", "Self-Employed",

        "Salaried", "Business", "Salaried", "Salaried", "Business",

        "Salaried", "Self-Employed", "Salaried", "Business", "Salaried"

    ],

    "Loan_Status": [

        "Approved", "Approved", "Approved", "Approved", "Rejected",

        "Approved", "Approved", "Rejected", "Approved", "Approved",

        "Approved", "Rejected", "Approved", "Rejected", "Approved",

        "Approved", "Approved", "Rejected", "Approved", "Approved"
    ]

}

df = pd.DataFrame(data)
print(df)

    Loan_ID  Applicant_Name  Age  Gender  Income  Loan_Amount  Loan_Term  \
0      1001    Rahul Sharma   28    Male   45000       250000          5   
1      1002     Priya Verma   35  Female   60000       400000         10   
2      1003      Amit Kumar   42    Male   75000       600000         15   
3      1004      Neha Singh   31  Female   52000       300000          7   
4      1005     Rohan Mehta   29    Male   48000       275000          5   
5      1006    Anjali Gupta   45  Female   90000       800000         20   
6      1007     Vikas Yadav   38    Male   68000       500000         15   
7      1008    Sneha Kapoor   27  Female   42000       200000          5   
8      1009  Arjun Malhotra   33    Male   80000       650000         20   
9      1010      Pooja Jain   40  Female   55000       350000         10   
10     1011     Karan Patel   36    Male   72000       550000         15   
11     1012     Simran Kaur   30  Female   65000       450000         10   
12     1013 

In [ ]:
df['Annual_Income']=df['Income']*12
print(df)

    Loan_ID  Applicant_Name  Age  Gender  Income  Loan_Amount  Loan_Term  \
0      1001    Rahul Sharma   28    Male   45000       250000          5   
1      1002     Priya Verma   35  Female   60000       400000         10   
2      1003      Amit Kumar   42    Male   75000       600000         15   
3      1004      Neha Singh   31  Female   52000       300000          7   
4      1005     Rohan Mehta   29    Male   48000       275000          5   
5      1006    Anjali Gupta   45  Female   90000       800000         20   
6      1007     Vikas Yadav   38    Male   68000       500000         15   
7      1008    Sneha Kapoor   27  Female   42000       200000          5   
8      1009  Arjun Malhotra   33    Male   80000       650000         20   
9      1010      Pooja Jain   40  Female   55000       350000         10   
10     1011     Karan Patel   36    Male   72000       550000         15   
11     1012     Simran Kaur   30  Female   65000       450000         10   
12     1013 

In [ ]:
df['Loan_Amount_Lakhsdf']=df['Loan_Amount']/10000
print(df)

    Loan_ID  Applicant_Name  Age  Gender  Income  Loan_Amount  Loan_Term  \
0      1001    Rahul Sharma   28    Male   45000       250000          5   
1      1002     Priya Verma   35  Female   60000       400000         10   
2      1003      Amit Kumar   42    Male   75000       600000         15   
3      1004      Neha Singh   31  Female   52000       300000          7   
4      1005     Rohan Mehta   29    Male   48000       275000          5   
5      1006    Anjali Gupta   45  Female   90000       800000         20   
6      1007     Vikas Yadav   38    Male   68000       500000         15   
7      1008    Sneha Kapoor   27  Female   42000       200000          5   
8      1009  Arjun Malhotra   33    Male   80000       650000         20   
9      1010      Pooja Jain   40  Female   55000       350000         10   
10     1011     Karan Patel   36    Male   72000       550000         15   
11     1012     Simran Kaur   30  Female   65000       450000         10   
12     1013 

In [ ]:
print(df[df['Income']>60000]['Applicant_Name'])

2         Amit Kumar
5       Anjali Gupta
6        Vikas Yadav
8     Arjun Malhotra
10       Karan Patel
11       Simran Kaur
12     Manish Sharma
14        Aditya Rao
16      Suresh Kumar
18       Varun Gupta
19      Kavita Singh
Name: Applicant_Name, dtype: object


In [ ]:
print(df[df['Loan_Amount']>500000]['Applicant_Name'])

2         Amit Kumar
5       Anjali Gupta
8     Arjun Malhotra
10       Karan Patel
12     Manish Sharma
16      Suresh Kumar
18       Varun Gupta
Name: Applicant_Name, dtype: object


In [ ]:
print(df[df['Credit_Score']>750]['Applicant_Name'])

5       Anjali Gupta
8     Arjun Malhotra
12     Manish Sharma
14        Aditya Rao
16      Suresh Kumar
Name: Applicant_Name, dtype: object


In [ ]:
print(df[df['Loan_Status']=="Approved"]['Applicant_Name'])

0       Rahul Sharma
1        Priya Verma
2         Amit Kumar
3         Neha Singh
5       Anjali Gupta
6        Vikas Yadav
8     Arjun Malhotra
9         Pooja Jain
10       Karan Patel
12     Manish Sharma
14        Aditya Rao
15     Nisha Agarwal
16      Suresh Kumar
18       Varun Gupta
19      Kavita Singh
Name: Applicant_Name, dtype: object


In [ ]:
print(df[df['Gender']=="Female"]['Applicant_Name'])

1       Priya Verma
3        Neha Singh
5      Anjali Gupta
7      Sneha Kapoor
9        Pooja Jain
11      Simran Kaur
13     Ritika Joshi
15    Nisha Agarwal
17       Meena Rani
19     Kavita Singh
Name: Applicant_Name, dtype: object


In [ ]:
print(df[df['Income']>50000]['Applicant_Name'])

1        Priya Verma
2         Amit Kumar
3         Neha Singh
5       Anjali Gupta
6        Vikas Yadav
8     Arjun Malhotra
9         Pooja Jain
10       Karan Patel
11       Simran Kaur
12     Manish Sharma
14        Aditya Rao
15     Nisha Agarwal
16      Suresh Kumar
18       Varun Gupta
19      Kavita Singh
Name: Applicant_Name, dtype: object


In [ ]:
print(df[df['Loan_Amount']==5000]['Applicant_Name'])

Series([], Name: Applicant_Name, dtype: object)


In [ ]:
print(df[(df['Age']>30) & (df['Loan_Status']=="Approved")])

    Loan_ID  Applicant_Name  Age  Gender  Income  Loan_Amount  Loan_Term  \
1      1002     Priya Verma   35  Female   60000       400000         10   
2      1003      Amit Kumar   42    Male   75000       600000         15   
3      1004      Neha Singh   31  Female   52000       300000          7   
5      1006    Anjali Gupta   45  Female   90000       800000         20   
6      1007     Vikas Yadav   38    Male   68000       500000         15   
8      1009  Arjun Malhotra   33    Male   80000       650000         20   
9      1010      Pooja Jain   40  Female   55000       350000         10   
10     1011     Karan Patel   36    Male   72000       550000         15   
12     1013   Manish Sharma   48    Male   95000       900000         20   
14     1015      Aditya Rao   34    Male   70000       500000         15   
15     1016   Nisha Agarwal   39  Female   58000       375000         10   
16     1017    Suresh Kumar   44    Male   85000       700000         20   
18     1019 

In [ ]:
print(df[(df['Employment_Type']=="Salaried") | (df['Gender']=="Male")])

    Loan_ID  Applicant_Name  Age  Gender  Income  Loan_Amount  Loan_Term  \
0      1001    Rahul Sharma   28    Male   45000       250000          5   
2      1003      Amit Kumar   42    Male   75000       600000         15   
3      1004      Neha Singh   31  Female   52000       300000          7   
4      1005     Rohan Mehta   29    Male   48000       275000          5   
5      1006    Anjali Gupta   45  Female   90000       800000         20   
6      1007     Vikas Yadav   38    Male   68000       500000         15   
7      1008    Sneha Kapoor   27  Female   42000       200000          5   
8      1009  Arjun Malhotra   33    Male   80000       650000         20   
10     1011     Karan Patel   36    Male   72000       550000         15   
12     1013   Manish Sharma   48    Male   95000       900000         20   
13     1014    Ritika Joshi   26  Female   40000       180000          5   
14     1015      Aditya Rao   34    Male   70000       500000         15   
15     1016 

In [ ]:
print(df[(df['Loan_Amount']>400000) | (df['Credit_Score']>780)])

    Loan_ID  Applicant_Name  Age  Gender  Income  Loan_Amount  Loan_Term  \
2      1003      Amit Kumar   42    Male   75000       600000         15   
5      1006    Anjali Gupta   45  Female   90000       800000         20   
6      1007     Vikas Yadav   38    Male   68000       500000         15   
8      1009  Arjun Malhotra   33    Male   80000       650000         20   
10     1011     Karan Patel   36    Male   72000       550000         15   
11     1012     Simran Kaur   30  Female   65000       450000         10   
12     1013   Manish Sharma   48    Male   95000       900000         20   
14     1015      Aditya Rao   34    Male   70000       500000         15   
16     1017    Suresh Kumar   44    Male   85000       700000         20   
18     1019     Varun Gupta   37    Male   78000       620000         15   
19     1020    Kavita Singh   41  Female   62000       420000         10   

    Credit_Score Employment_Type Loan_Status  Annual_Income  \
2            750        